# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lecture7App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lecture7App
	pod 'PinLayout'

end
