# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Technoblog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Technoblog
	pod 'Firebase/Analytics'
	pod 'Firebase/Firestore'
	pod 'Firebase/Storage'
	pod 'PinLayout'

end
