# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DataStorage' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  pod 'Static'
  pod 'Log'
  pod 'Gloss'
  pod 'RealmSwift'
  
  # Pods for DataStorage

end
